# Generated by Django 4.2.9 on 2024-05-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='recipies',
            options={'verbose_name_plural': 'recipies'},
        ),
        migrations.AddField(
            model_name='recipies',
            name='ingredients',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='recipies',
            name='instructions',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
