# Generated by Django 4.2.9 on 2024-07-17 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheff', '0002_alter_category_options_alter_recipies_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=1)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheff.recipies')),
            ],
        ),
    ]
