# Generated by Django 4.2.9 on 2024-07-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheff', '0003_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='rating',
            field=models.FloatField(max_length=1),
        ),
    ]
